spring.application.name=recurring_deposit

spring.datasource.url = jdbc:postgresql://localhost:5400/recurring_deposit
spring.datasource.username = postgres
spring.datasource.password = Sayyed786@

spring.jpa.hibernate.ddl-auto = update

server.port = 8080